In [1]:
import common
from db import get_engine
engine = get_engine()

Microsoft SQL Server 2022 (RTM-CU27-GDR) (KB5126934) - 16.0.
Logged in as: datacube_analytics
     name
0  bronze
1    gold
2  silver

In [2]:
airlines_raw = common.pd.read_csv('/workspaces/Flight-delay-analysis-E2E/data/Flight/airlines.csv')

In [3]:
airports_raw = common.pd.read_csv('/workspaces/Flight-delay-analysis-E2E/data/Flight/airports.csv')

In [4]:
flights_raw = common.pd.read_parquet('/workspaces/Flight-delay-analysis-E2E/data/Flight/flights.parquet')

In [5]:
flights_raw.head(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN

In [6]:
hava = common.pd.read_parquet('/workspaces/Flight-delay-analysis-E2E/data/api/weather_2015_all.parquet')

In [7]:
hava.head()

,airport_code,observation_time,Latitude,Longitude,temperature,precipitation,wind_speed,visibility,weather_condition,surface_pressure,wind_direction,snowfall,wind_gusts
0,ABE,2015-01-01 00:00:00,40.65236,-75.4404,-4.4,0.0,7.7,NaN,0,1009.3,242,0.0,20.9
1,ABE,2015-01-01 01:00:00,40.65236,-75.4404,-4.7,0.0,8.0,NaN,0,1009.0,243,0.0,23.0
2,ABE,2015-01-01 02:00:00,40.65236,-75.4404,-4.9,0.0,10.4,NaN,0,1008.3,250,0.0,25.2
3,ABE,2015-01-01 03:00:00,40.65236,-75.4404,-5.0,0.0,12.1,NaN,0,1008.0,253,0.0,25.6
4,ABE,2015-01-01 04:00:00,40.65236,-75.4404,-5.0,0.0,12.0,NaN,0,1007.5,249,0.0,26.6

In [8]:
airports_raw

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447
...,...,...,...,...,...,...,...
317,WRG,Wrangell Airport,Wrangell,AK,USA,56.48433,-132.36982
318,WYS,Westerly State Airport,West Yellowstone,MT,USA,44.68840,-111.11764
319,XNA,Northwest Arkansas Regional Airport,Fayetteville/Springdale/Rogers,AR,USA,36.28187,-94.30681
320,YAK,Yakutat Airport,Yakutat,AK,USA,59.50336,-139.66023
321,YUM,Yuma International Airport,Yuma,AZ,USA,32.65658,-114.60597