In [1]:
from common import *
engine = get_engine()

In [4]:
count = pd.read_sql(text(f"SELECT COUNT(*) AS row_count  FROM bronze.flights"), engine)
count

OperationalError: (pymssql.exceptions.OperationalError) (18456, b"Login failed for user 'datacube_analytics'.DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nTDS server connection failed (localhost)\nDB-Lib error message 20002, severity 9:\nTDS server connection failed (localhost)\n")
(Background on this error at: https://sqlalche.me/e/21/e3q8)

In [7]:
count = pd.read_sql(text(f"SELECT COUNT(*) AS row_count FROM bronze.weather"), engine)
count

   row_count
0    2225040

In [2]:
pd.read_sql(text(f"SELECT * FROM bronze.airlines"), engine).head(10)

  IATA_CODE                 AIRLINE
0        UA   United Air Lines Inc.
1        AA  American Airlines Inc.
2        US         US Airways Inc.
3        F9  Frontier Airlines Inc.
4        B6         JetBlue Airways
5        OO   Skywest Airlines Inc.
6        AS    Alaska Airlines Inc.
7        NK        Spirit Air Lines
8        WN  Southwest Airlines Co.
9        DL    Delta Air Lines Inc.

In [3]:
pd.read_sql(text(f'select * from bronze.airports'), engine).head(5)

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447